const DUNTA_SUPABASE_URL='https://keonvsakkkzxnxxduacz.supabase.co';
const DUNTA_SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtlb252c2Fra2t6eG54eGR1YWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg2MDUxODQsImV4cCI6MjEwNDE4MTE4NH0.cgiVTH4txAUPwpQozH7AmGergXHIPGpPEFKHU2LBMHg';
const DUNTA_DRIVER_RADIUS_KM=10;
const DUNTA_COUNTRIES=[["AO","+244"],["PT","+351"],["BR","+55"],["MZ","+258"],["CV","+238"],["US","+1"]];
let selectedRole='passenger',selectedVehicle='any',pendingDestination='';
let duntaSupabase=null,duntaMap=null,duntaMe=null,duntaWatch=null,duntaAccuracy=null;
let duntaDrivers=new Map(),duntaPassengerLocation=null,duntaDriverRecordId=null,duntaLocationTimer=null;
let duntaActiveRide=null,duntaRideChannel=null,duntaIncomingRequest=null,routeLine=null;
let duntaMeMarker=null,duntaPassengerMarker=null,duntaLiveRideTimer=null,duntaBooted=false;
const countrySelect=document.getElementById('country');
DUNTA_COUNTRIES.forEach(([c,d])=>{const o=document.createElement('option');o.value=c;o.textContent=d;o.dataset.dial=d;countrySelect.appendChild(o)});
countrySelect.value='AO';
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>e.classList.remove('show'),1800)}
function supa(t,c){const e=document.getElementById('supa');e.textContent=t;e.className=c||'';e.style.display='block';if(c==='ok')setTimeout(()=>e.style.display='none',1800)}
function getSession(){try{return JSON.parse(localStorage.getItem('dunta_session')||'null')}catch(e){return null}}
function saveSession(s){if(s)localStorage.setItem('dunta_session',JSON.stringify(s));else localStorage.removeItem('dunta_session')}
function showAuth(w){['auth-start','auth-login','auth-register'].forEach(id=>document.getElementById(id).classList.add('hidden'));document.getElementById('auth-'+w).classList.remove('hidden')}
function selectRole(r){selectedRole=r;document.getElementById('role-passenger').classList.toggle('on',r==='passenger');document.getElementById('role-driver').classList.toggle('on',r==='driver');document.getElementById('driver-fields').classList.toggle('hidden',r!=='driver')}
function fullPhone(id){const o=countrySelect.options[countrySelect.selectedIndex];return (o?.dataset.dial||'+244')+' '+document.getElementById(id).value.trim()}
function authEmail(email){return email.trim().toLowerCase()}
function getProfileAvatar(){const s=getSession();return s?.avatar_url||''}
function avatarHtml(url,name='Utilizador',cls='profile-avatar'){return url?`<img class="${cls}" src="${url}" alt="Foto de ${name}" loading="lazy">`:`<div class="avatar-fallback ${cls}" style="display:grid;place-items:center"><i class="fa-solid fa-user"></i></div>`}
function previewRegisterAvatar(input){const f=input?.files?.[0];if(!f)return;const url=URL.createObjectURL(f);const el=document.getElementById('register-avatar-preview');if(el)el.innerHTML=`<img class="profile-avatar" style="width:54px;height:54px" src="${url}" alt="Pré-visualização">`}
async function uploadAvatarFile(file,userId){if(!file||!userId||!duntaSupabase)return null;if(!file.type.startsWith('image/')){toast('Escolha uma imagem');return null}if(file.size>5*1024*1024){toast('A foto deve ter no máximo 5 MB');return null}const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${userId}/avatar.${ext}`;const {error:up}=await duntaSupabase.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(up){console.error(up);toast('Não foi possível guardar a foto');return null}const {data}=duntaSupabase.storage.from('avatars').getPublicUrl(path);return data?.publicUrl?`${data.publicUrl}?v=${Date.now()}`:null}
async function uploadProfilePhoto(input){const f=input?.files?.[0];if(!f||!duntaSupabase)return;const s=getSession();if(!s?.id){toast('Faça login novamente');return}const url=await uploadAvatarFile(f,s.id);if(!url)return;const {error}=await duntaSupabase.from('profiles').update({avatar_url:url,updated_at:new Date().toISOString()}).eq('id',s.id);if(error){console.error(error);toast('Erro ao atualizar perfil');return}saveSession({...s,avatar_url:url});refreshAccount();toast('Foto de perfil atualizada')}
function setAccountAvatar(url){const el=document.getElementById('account-avatar');if(!el)return;el.innerHTML=url?`<img class="profile-avatar" src="${url}" alt="Foto de perfil">`:'<i class="fa-solid fa-user real-icon" style="font-size:34px"></i>'}

async function doRegister(){
 const name=document.getElementById('reg-name').value.trim(), email=document.getElementById('reg-email').value.trim().toLowerCase(), phone=fullPhone('reg-phone'), pass=document.getElementById('reg-pass').value;
 if(!name||!email||!email.includes('@')||!phone||pass.length<6){toast('Preencha nome, e-mail, telefone e senha (mín. 6)');return}
 const avatarFile=document.getElementById('reg-avatar')?.files?.[0];if(!avatarFile){toast('Escolha uma foto de perfil');return}
 if(selectedRole==='driver'&&!document.getElementById('vehicle').value){toast('Escolha o veículo');return}
 if(!duntaSupabase){await initSupabase();if(!duntaSupabase){toast('Servidor indisponível');return}}
 const {data,error}=await duntaSupabase.auth.signUp({email,password:pass,options:{data:{name,phone,role:selectedRole,vehicle:document.getElementById('vehicle')?.value||null,vehicle_id:document.getElementById('vehicle-id')?.value||null}}});
 if(error){toast(error.message.includes('already')?'Este e-mail já está registado':'Erro ao criar conta');console.error(error);return}
 let avatar_url=null;if(data.session){avatar_url=await uploadAvatarFile(avatarFile,data.user.id);if(!avatar_url){toast('Não foi possível guardar a foto');return}}
 const profile={id:data.user.id,name,phone,email,role:selectedRole,vehicle:document.getElementById('vehicle')?.value||null,vehicle_id:document.getElementById('vehicle-id')?.value||null,avatar_url};
 const {error:pe}=await duntaSupabase.from('profiles').upsert(profile);if(pe){console.error(pe);toast('Conta criada, mas não foi possível guardar o perfil');return}
 if(!data.session){showDuntaSplash(()=>{toast('Conta criada. Confirme o seu e-mail para poder entrar.');showAuth('login');});return}
 const s={...profile,vehicleId:profile.vehicle_id,online:false};saveSession(s);showDuntaSplash(()=>enterApp())
}
async function doLogin(){
 const email=document.getElementById('login-email').value.trim().toLowerCase(),pass=document.getElementById('login-pass').value;
 if(!email||!email.includes('@')||!pass){toast('E-mail e senha são obrigatórios');return}
 if(!duntaSupabase){await initSupabase();if(!duntaSupabase){toast('Servidor indisponível');return}}
 const {data,error}=await duntaSupabase.auth.signInWithPassword({email,password:pass});
 if(error){toast('E-mail ou senha incorretos');return}
 const {data:p}=await duntaSupabase.from('profiles').select('id,name,phone,email,role,vehicle,vehicle_id,avatar_url').eq('id',data.user.id).single();
 if(!p){toast('Perfil não encontrado');await duntaSupabase.auth.signOut();return}
 const old=getSession()||{};saveSession({...p,email:p.email||data.user.email,vehicleId:p.vehicle_id,online:old.online||false});showDuntaSplash(()=>enterApp())
}
async function logout(){if(!confirm('Terminar sessão?'))return;stopDriverSync();if(duntaSupabase)await duntaSupabase.auth.signOut();saveSession(null);location.reload()}
function showDuntaSplash(after){
 const old=document.getElementById('dunta-splash');
 if(old)old.remove();
 const splash=document.createElement('div');
 splash.id='dunta-splash';
 splash.innerHTML=`<div class="dunta-splash-logo"><svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Logotipo DUNTA TAXI">
 <defs><linearGradient id="bgRedSplash" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#FF3B2E"/><stop offset="100%" stop-color="#C10F06"/></linearGradient><linearGradient id="yellowSplash" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#FFEB6B"/><stop offset="100%" stop-color="#FFC400"/></linearGradient></defs>
 <rect x="0" y="0" width="512" height="512" rx="112" fill="url(#bgRedSplash)"/>
 <g class="splash-lines" stroke="#FFFFFF" stroke-width="14" stroke-linecap="round"><line x1="330" y1="90" x2="440" y2="90"/><line x1="360" y1="130" x2="450" y2="130"/><line x1="390" y1="170" x2="452" y2="170"/></g>
 <g transform="translate(256,270)"><g class="splash-mono"><path d="M-140 -120 L-60 -120 C10 -120 60 -68 60 0 C60 68 10 120 -60 120 L-140 120 Z M-84 -68 L-84 68 L-60 68 C-12 68 8 34 8 0 C8 -34 -12 -68 -60 -68 Z" fill="url(#yellowSplash)" fill-rule="evenodd"/><path d="M40 -120 L172 -120 L172 -68 L134 -68 L134 120 L78 120 L78 -68 L40 -68 Z" fill="#FFFFFF"/></g></g>
 <g transform="translate(256,392)"><g class="splash-swoosh"><path d="M-150 20 C-80 -20 80 -20 150 20 L130 44 C70 12 -70 12 -130 44 Z" fill="url(#yellowSplash)"/></g></g></svg></div>`;
 document.body.appendChild(splash);
 setTimeout(()=>{splash.classList.add('splash-hide');setTimeout(()=>{splash.remove();if(typeof after==='function')after()},260)},2100);
}
function enterApp(){document.getElementById('auth').classList.add('hidden');document.getElementById('app').classList.remove('hidden');refreshAccount();setTimeout(()=>{initMap();initSupabase()},150)}
function refreshAccount(){const s=getSession();if(!s)return;document.getElementById('acc-name-view').textContent=s.name||'Utilizador';document.getElementById('acc-phone-view').textContent=s.phone||'—';setAccountAvatar(s.avatar_url||'');const card=document.getElementById('driver-online-card');if(s.role==='driver'){card.style.display='block';document.getElementById('online-label').textContent=s.online?'Estado: Online':'Estado: Offline'}else card.style.display='none'}
function openPanel(n){closePanels();document.getElementById('panel-'+n)?.classList.add('open');if(n==='account')refreshAccount();if(n==='history')loadHistory()}
function closePanels(){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('open'))}
function goRegisterDriver(){localStorage.removeItem('dunta_session');document.getElementById('auth').classList.remove('hidden');document.getElementById('app').classList.add('hidden');showAuth('register');selectRole('driver')}
function startTripFlow(type){pickVehicle(type);document.getElementById('home').style.display='none';document.getElementById('req').classList.add('show');document.getElementById('map-back').style.display='grid';document.getElementById('map-loc').style.display='grid';if(duntaMap)setTimeout(()=>duntaMap.invalidateSize(),200);if(!pendingDestination)openPanel('search')}
function closeRequest(){document.getElementById('req').classList.remove('show');document.getElementById('home').style.display='block';document.getElementById('map-back').style.display='none';document.getElementById('map-loc').style.display='none';document.getElementById('eta').style.display='none';if(routeLine&&duntaMap){duntaMap.removeLayer(routeLine);routeLine=null}}
function pickVehicle(t){selectedVehicle=t;['any','mota','taxi'].forEach(v=>document.getElementById('v-'+v)?.classList.toggle('on',v===t))}
function pickPlace(name){pendingDestination=name;document.getElementById('destination').value=name;document.getElementById('dest-label').textContent=name;document.getElementById('dest-sub').textContent='Destino selecionado';closePanels();if(document.getElementById('home').style.display!=='none')startTripFlow(selectedVehicle||'any');drawFakeRoute()}
function confirmDestination(){const d=document.getElementById('destination').value.trim();if(!d){toast('Indique o destino');return}pickPlace(d)}
function confirmRequest(){if(!pendingDestination){openPanel('search');toast('Indique o destino');return}const btn=document.getElementById('btn-request');btn.disabled=true;btn.textContent='A procurar…';requestRide(selectedVehicle).finally(()=>{btn.disabled=false;btn.textContent='Pedir'})}
function setPassengerMarker(lat,lng,name,avatar){if(!duntaMap)return;const html=avatar?`<div class="live-avatar"><img src="${avatar}" alt=""></div>`:`<div class="live-avatar fallback"><i class="fa-solid fa-user"></i></div>`;const icon=L.divIcon({className:'',html,iconSize:[46,46],iconAnchor:[23,23]});if(!duntaPassengerMarker)duntaPassengerMarker=L.marker([lat,lng],{icon,zIndexOffset:900}).addTo(duntaMap);else{duntaPassengerMarker.setLatLng([lat,lng]);duntaPassengerMarker.setIcon(icon)}duntaPassengerMarker.bindPopup(`<b>${name||'Passageiro'}</b><br>Localização em tempo real`)}
async function updateActiveRidePassengerPosition(lat,lng){const s=getSession();if(!s||s.role!=='passenger'||!duntaActiveRide||!duntaSupabase)return;if(!['pending','accepted'].includes(duntaActiveRide.status))return;const now=Date.now();if(updateActiveRidePassengerPosition._last&&now-updateActiveRidePassengerPosition._last<2500)return;updateActiveRidePassengerPosition._last=now;await duntaSupabase.from('ride_requests').update({passenger_lat:lat,passenger_lng:lng,updated_at:new Date().toISOString()}).eq('id',duntaActiveRide.id).eq('passenger_id',s.id)}
function watchRidePassenger(id){if(!duntaSupabase||!id)return;if(duntaRideChannel)try{duntaSupabase.removeChannel(duntaRideChannel)}catch(e){}duntaRideChannel=duntaSupabase.channel('ride-live-'+id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'ride_requests',filter:`id=eq.${id}`},payload=>{const r=payload.new;duntaActiveRide=r;if(r.passenger_lat&&r.passenger_lng&&getSession()?.role==='driver')setPassengerMarker(+r.passenger_lat,+r.passenger_lng,r.passenger_name,r.passenger_avatar_url);handleRideUpdate(r)}).subscribe()}
function handleRideUpdate(r){if(r.status==='accepted'&&getSession()?.role==='passenger'){showBan(`<div class="request-person">${avatarHtml(r.driver_avatar_url,r.driver_name||'Motorista','profile-avatar small')}<div><div class="rp-name">${r.driver_name||'Motorista'}</div><div class="rp-meta">${r.driver_vehicle_type==='mota'?'Mototáxi':'Táxi'} · Motorista a caminho</div></div></div>`);if(r.driver_location_id){}notify('Motorista a caminho',r.driver_name||'')}else if(r.status==='cancelled'){showBan('Pedido cancelado');setTimeout(()=>showBan(''),2500)}else if(r.status==='completed'){showBan('Viagem concluída');setTimeout(()=>showBan(''),3000)}}
function initMap(){if(duntaMap)return;duntaMap=L.map('map',{zoomControl:false,attributionControl:true}).setView([-8.8383,13.2344],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OSM'}).addTo(duntaMap);L.control.zoom({position:'bottomright'}).addTo(duntaMap);setTimeout(()=>duntaMap.invalidateSize(),100);startGPS()}
function distanceKm(a,b,c,d){const R=6371,r=Math.PI/180,x=(c-a)*r,y=(d-b)*r;const s=Math.sin(x/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
function driverIcon(type){const cls=type==='mota'?'mota':'';const icon=type==='mota'?'fa-motorcycle':'fa-taxi';return L.divIcon({className:'',html:`<div class="driver-fa-marker ${cls}"><i class="fa-solid ${icon}"></i></div>`,iconSize:[42,42],iconAnchor:[21,21]})}
function setMe(lat,lng,acc){const ll=[lat,lng];if(!duntaMe)duntaMe=L.circleMarker(ll,{radius:8,color:'#fff',weight:3,fillColor:'#2563EB',fillOpacity:1}).addTo(duntaMap);else duntaMe.setLatLng(ll);if(!duntaAccuracy)duntaAccuracy=L.circle(ll,{radius:acc||30,weight:0,fillColor:'#2563EB',fillOpacity:.12}).addTo(duntaMap);else duntaAccuracy.setLatLng(ll).setRadius(acc||30);duntaPassengerLocation={lat,lng,accuracy:acc||null};document.getElementById('home-loc').textContent='GPS ativo';document.getElementById('origin-label').textContent='A minha localização';savePassengerLocation(lat,lng,acc);loadNearbyDrivers()}
function startGPS(){if(!navigator.geolocation){toast('GPS indisponível');return}if(duntaWatch)navigator.geolocation.clearWatch(duntaWatch);duntaWatch=navigator.geolocation.watchPosition(p=>setMe(p.coords.latitude,p.coords.longitude,p.coords.accuracy),()=>toast('Ative a localização'),{enableHighAccuracy:true,maximumAge:4000,timeout:12000})}
function recenter(){if(duntaMe)duntaMap.setView(duntaMe.getLatLng(),15)}
function addDriver(id,name,type,lat,lng,avatar){if(!duntaMap)return;if(duntaPassengerLocation){const dist=distanceKm(duntaPassengerLocation.lat,duntaPassengerLocation.lng,lat,lng);if(dist>DUNTA_DRIVER_RADIUS_KM){clearDriver(id);return}}if(duntaDrivers.has(id))duntaDrivers.get(id).setLatLng([lat,lng]);else{const m=L.marker([lat,lng],{icon:driverIcon(type)}).addTo(duntaMap);m.bindPopup(`${avatarHtml(avatar,name,'profile-avatar small')}<br><b>${name||'Motorista'}</b><br>${type==='mota'?'Mota':'Táxi'}`);duntaDrivers.set(id,m)}}
function clearDriver(id){const m=duntaDrivers.get(id);if(m){duntaMap.removeLayer(m);duntaDrivers.delete(id)}}
function drawFakeRoute(){if(!duntaMap||!duntaMe)return;const p=duntaMe.getLatLng();const end=[p.lat+0.012,p.lng+0.018];if(routeLine)duntaMap.removeLayer(routeLine);routeLine=L.polyline([[p.lat,p.lng],[p.lat+0.004,p.lng+0.006],[p.lat+0.009,p.lng+0.011],end],{color:'#16A34A',weight:5,opacity:.9}).addTo(duntaMap);duntaMap.fitBounds(routeLine.getBounds(),{padding:[60,60]});const eta=document.getElementById('eta');eta.style.display='block';eta.innerHTML='~12 min<small>estimativa de trajeto</small>'}
async function initSupabase(){
 if(!window.supabase){supa('Falha ao carregar Supabase','err');return false}
 if(duntaSupabase)return true;
 duntaSupabase=window.supabase.createClient(DUNTA_SUPABASE_URL,DUNTA_SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
 const {data:{session}}=await duntaSupabase.auth.getSession();
 if(!session){if(getSession()){saveSession(null);document.getElementById('auth').classList.remove('hidden');document.getElementById('app').classList.add('hidden')}return false}
 const {data:p,error}=await duntaSupabase.from('profiles').select('id,name,phone,role,vehicle,vehicle_id,avatar_url').eq('id',session.user.id).single();
 if(error||!p){console.error(error);supa('Perfil não encontrado','err');return false}
 const old=getSession()||{};saveSession({...p,vehicleId:p.vehicle_id,online:old.online||false});
 const test=await duntaSupabase.from('drivers_locations').select('id').limit(1);
 if(test.error){supa('Execute supabase_schema.sql','err');return false}
 supa('Ligado','ok');await loadNearbyDrivers();subscribeDrivers();
 if(p.role==='driver'){subscribeRideRequests();if(old.online)startDriverSync()}
 return true
}
async function loadNearbyDrivers(){if(!duntaSupabase)return;const {data}=await duntaSupabase.from('drivers_locations').select('id,driver_name,vehicle_type,avatar_url,latitude,longitude,is_online').eq('is_online',true);const active=new Set();(data||[]).forEach(d=>{const lat=+d.latitude,lng=+d.longitude;if(Number.isFinite(lat)&&Number.isFinite(lng)){active.add(d.id);addDriver(d.id,d.driver_name,d.vehicle_type,lat,lng,d.avatar_url)}});[...duntaDrivers.keys()].forEach(id=>{if(!active.has(id))clearDriver(id)})}
function subscribeDrivers(){duntaSupabase.channel('drivers-live').on('postgres_changes',{event:'*',schema:'public',table:'drivers_locations'},payload=>{if(payload.eventType==='DELETE'){clearDriver(payload.old?.id);return}const d=payload.new;if(!d?.is_online){clearDriver(d?.id);return}if(Number.isFinite(+d.latitude)&&Number.isFinite(+d.longitude))addDriver(d.id,d.driver_name,d.vehicle_type,d.latitude,d.longitude)}).subscribe()}
async function savePassengerLocation(lat,lng,acc){if(!duntaSupabase)return;const s=getSession();if(!s||s.role==='driver')return;await duntaSupabase.from('passenger_locations').upsert({passenger_id:s.id,passenger_phone:s.phone,latitude:lat,longitude:lng,accuracy:acc||null,updated_at:new Date().toISOString()},{onConflict:'passenger_id'})}
async function publishDriverLocation(){if(!duntaSupabase||!duntaMe)return;const s=getSession();if(!s||s.role!=='driver')return;const p=duntaMe.getLatLng();const rec={driver_id:s.id,driver_name:s.name||'Motorista',avatar_url:s.avatar_url||null,vehicle_type:s.vehicle||'taxi',phone:s.phone,latitude:p.lat,longitude:p.lng,is_online:true,updated_at:new Date().toISOString()};
const {data,error}=await duntaSupabase.from('drivers_locations').upsert(rec,{onConflict:'driver_id'}).select().single();
if(error)console.error(error); else if(data)duntaDriverRecordId=data.id}
function startDriverSync(){if(duntaLocationTimer)clearInterval(duntaLocationTimer);duntaLocationTimer=setInterval(publishDriverLocation,10000);publishDriverLocation()}
function stopDriverSync(){if(duntaLocationTimer)clearInterval(duntaLocationTimer);duntaLocationTimer=null}
async function toggleOnline(){const s=getSession();if(!s||s.role!=='driver')return;s.online=!s.online;saveSession(s);refreshAccount();if(s.online){toast('Online');startDriverSync()}else{toast('Offline');stopDriverSync();if(duntaSupabase&&duntaDriverRecordId)await duntaSupabase.from('drivers_locations').update({is_online:false,updated_at:new Date().toISOString()}).eq('id',duntaDriverRecordId)}}
async function requestRide(vehicleType){const s=getSession();if(!s){toast('Faça login');return}if(s.role==='driver'){toast('Conta de motorista');return}if(!duntaSupabase){await initSupabase();if(!duntaSupabase){toast('Sem servidor');return}}let lat,lng;if(duntaPassengerLocation){lat=duntaPassengerLocation.lat;lng=duntaPassengerLocation.lng}else if(duntaMe){const p=duntaMe.getLatLng();lat=p.lat;lng=p.lng}else{toast('Ative o GPS');return}showBan('A procurar motorista…');const payload={passenger_id:s.id,passenger_phone:s.phone,passenger_name:s.name||'Passageiro',passenger_avatar_url:s.avatar_url||null,passenger_lat:lat,passenger_lng:lng,destination:pendingDestination||'Destino',vehicle_type:vehicleType||'any',status:'pending',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {data,error}=await duntaSupabase.from('ride_requests').insert(payload).select().single();if(error){console.error(error);showBan('');toast('Erro ao pedir');return}duntaActiveRide=data;listenMyRide(data.id);showBan('Pedido enviado — à espera de motorista')}
function showBan(html){const el=document.getElementById('ban');if(!html){el.style.display='none';return}el.innerHTML=html;el.style.display='block'}
function listenMyRide(id){if(!duntaSupabase)return;if(duntaRideChannel)try{duntaSupabase.removeChannel(duntaRideChannel)}catch(e){}duntaRideChannel=duntaSupabase.channel('ride-'+id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'ride_requests',filter:`id=eq.${id}`},payload=>{const r=payload.new;duntaActiveRide=r;handleRideUpdate(r)}).subscribe()}

function subscribeRideRequests(){const s=getSession();if(!s||s.role!=='driver')return;duntaSupabase.channel('req-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'ride_requests'},payload=>{const req=payload.new;if(req.status!=='pending')return;if(req.vehicle_type!=='any'&&req.vehicle_type!==(s.vehicle||'taxi'))return;if(duntaMe){const p=duntaMe.getLatLng();if(distanceKm(p.lat,p.lng,req.passenger_lat,req.passenger_lng)>DUNTA_DRIVER_RADIUS_KM)return}showDriverRequest(req)}).subscribe()}
function showDriverRequest(req){duntaIncomingRequest=req;let dist='?';if(duntaMe){const p=duntaMe.getLatLng();dist=distanceKm(p.lat,p.lng,req.passenger_lat,req.passenger_lng).toFixed(1)}document.getElementById('req-person').innerHTML=`<div class="request-person">${avatarHtml(req.passenger_avatar_url,req.passenger_name||'Passageiro','profile-avatar small')}<div><div class="rp-name">${req.passenger_name||'Passageiro'}</div><div class="rp-meta">Passageiro verificado por foto</div></div></div>`;document.getElementById('req-info').innerHTML=`Destino: <b>${req.destination||'—'}</b><br>Tipo: ${req.vehicle_type==='mota'?'Mota':req.vehicle_type==='taxi'?'Táxi':'Qualquer'}<br>~${dist} km`;document.getElementById('dm').classList.add('show');notify('Novo pedido DUNTA',req.passenger_name||'')}
async function acceptRide(){if(!duntaIncomingRequest||!duntaSupabase)return;const s=getSession(),req=duntaIncomingRequest;document.getElementById('dm').classList.remove('show');const {data,error}=await duntaSupabase.from('ride_requests').update({status:'accepted',driver_id:s.id,driver_location_id:duntaDriverRecordId,driver_name:s.name,driver_avatar_url:s.avatar_url||null,driver_phone:s.phone,driver_vehicle_type:s.vehicle||'taxi',updated_at:new Date().toISOString()}).eq('id',req.id).eq('status','pending').select().single();if(error||!data){toast('Já aceite por outro');return}duntaActiveRide=data;watchRidePassenger(data.id);if(data.passenger_lat&&data.passenger_lng)setPassengerMarker(+data.passenger_lat,+data.passenger_lng,data.passenger_name,data.passenger_avatar_url);showBan(`Dirija-se a ${data.passenger_name||'passageiro'}`);if(duntaMap)duntaMap.setView([data.passenger_lat,data.passenger_lng],15);duntaIncomingRequest=null}
function rejectRide(){document.getElementById('dm').classList.remove('show');duntaIncomingRequest=null}
async function loadHistory(){const box=document.getElementById('history-list');box.innerHTML='<div style="padding:16px;color:#6B7280;font-size:14px">A carregar…</div>';const s=getSession();if(!s||!duntaSupabase){box.innerHTML='<div style="padding:16px;color:#6B7280">Sem dados</div>';return}let q=duntaSupabase.from('ride_requests').select('destination,vehicle_type,status,driver_name,created_at').order('created_at',{ascending:false}).limit(20);q=s.role==='driver'?q.eq('driver_phone',s.phone):q.eq('passenger_phone',s.phone);const {data,error}=await q;if(error||!data?.length){box.innerHTML='<div style="padding:16px;color:#6B7280">Ainda não há viagens</div>';return}box.innerHTML=data.map(r=>{const st={pending:'Pendente',accepted:'Aceite',completed:'Concluída',cancelled:'Cancelada'}[r.status]||r.status;const when=r.created_at?new Date(r.created_at).toLocaleString('pt'):'';return `<div class="lr"><span class="li"><svg class="i" viewBox="0 0 24 24"><path d="M4 16h16v-2l-1.5-4.5h-13L4 14v2z"/><circle cx="7.5" cy="16.5" r="1.2"/><circle cx="16.5" cy="16.5" r="1.2"/></svg></span><span class="bd"><b>${r.destination||'Viagem'}</b><small>${when} · ${st}</small></span></div>`}).join('')}
async function askNotif(){if(!('Notification' in window)){toast('Não suportado');return}if(Notification.permission==='granted'){toast('Já ativas');return}const p=await Notification.requestPermission();toast(p==='granted'?'Ativadas':'Negadas')}
function notify(title,body){if(!('Notification' in window)||Notification.permission!=='granted')return;try{new Notification(title,{body,icon:'./icon-192.png'})}catch(e){}}
document.addEventListener('click',function once(){askNotif();document.removeEventListener('click',once)},{once:true});
(function(){if(getSession())enterApp();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})();

window.addEventListener('error',e=>{console.error('DUNTA:',e.error||e.message);try{toast('Erro interno. Recarregue a app.')}catch(_){} });
window.addEventListener('unhandledrejection',e=>{console.error('DUNTA promise:',e.reason)});
document.addEventListener('DOMContentLoaded',()=>{duntaBooted=true;try{const s=getSession();if(s){document.getElementById('auth').classList.add('hidden');document.getElementById('app').classList.remove('hidden');refreshAccount();setTimeout(()=>{initMap();initSupabase()},80)}}catch(e){console.error(e)}});
